### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by amandabradi** [sangaline/scrapy-wayback-machine#5]
Hi, this is written very confusingly. Can you help me out with the installation of scrapy and this program? I have little expericence with python.

Thanks,
**Amanda**.

**Comment by sangaline** [comment]
If you're not familiar with Scrapy or Python, then you probably want to start with the CLI program [scrapy-wayback-machine](https://github.com/sangaline/wayback-machine-scraper). That program uses this Scrapy middleware under the hood without requiring any programming. You can run the CLI to download page snapshots, and then parse them in a programming language of your choice.
